[build]
  command = "npm run build" 
  functions = "functions" 

[functions]
  directory = "functions"
  node_bundler = "esbuild" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
