[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.environment]
FIRESTORE_KEY = "DL7AO48wWye1fvfusK66"

[build]
functions = ["script.php"]

[functions]
directory = "functions"
