[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
functions = ["script.php"]

[functions]
directory = "functions"

[context.environment]
FIRESTORE_KEY = file("./firestore_key.json")
