[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
functions = ["script.php"]

[functions]
directory = "functions"

[context.environment]
FIRESTORE_KEY = "1090344054498-rtiv75001alrgfgtbqo01c2iv2rn90l1.apps.googleusercontent.com"
