[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
functions = ["script.php"]
publish = "dist"

[functions]
directory = "functions"
node_modules = "node_modules"

[context.env]
  FIREBASE_PROJECT_ID = "tanzania-408718"
  FIREBASE_CLIENT_ID = "1090344054498-rtiv75001alrgfgtbqo01c2iv2rn90l1.apps.googleusercontent.com"
  FIREBASE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
  FIREBASE_TOKEN_URI = "https://oauth2.googleapis.com/token"
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"

[context.globalData]
  firebase = {
    apiKey = "",
    authDomain = "",
    projectId = "tanzania-408718",
    storageBucket = "",
    databaseURL = "",
  }


  
